// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwptlshkdbmvbhxlgwtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13cHRsc2hrZGJtdmJoeGxnd3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjIxNzYsImV4cCI6MjA1NTA5ODE3Nn0.SNffLuhS61_mK8c8u_7sc1vndnJ_gyjTcji-dVoGjtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);